name: Build and Push Docker Image to ECR

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Log in to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1
      #   with:
      #     region: ${{ secrets.AWS_REGION }}
      #     access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Build Docker image
      #   run: |
      #     docker build -t threemay/goexpertbackendtest .

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com
          ECR_REPOSITORY: <your-repository-name>
          IMAGE_TAG: latest
        run: |
          # export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          # export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
          aws sts get-caller-identity
          docker build -t threemay/goexpertbackendtest:latest1 .
          docker tag threemay/goexpertbackendtest:latest1 public.ecr.aws/a9h1i7z6/threemay/goexpertbackendtest:latest1
          docker push public.ecr.aws/a9h1i7z6/threemay/goexpertbackendtest:latest1
