name: Build and Push Node.js Docker Image to AWS ECR

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          image_tag=${{ github.sha }}
          echo "IMAGE_TAG=$image_tag" >> $GITHUB_ENV 
          docker build -t cms-backend:$image_tag .

      - name: Tag Docker Image
        run: |
          docker tag ben:${{ env.IMAGE_TAG }} ${{ secrets.REPO_URI }}:${{ env.IMAGE_TAG }}
          docker tag ben:${{ env.IMAGE_TAG }} ${{ secrets.REPO_URI }}:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.REPO_URI }}:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.REPO_URI }}:latest
